name: flutter_cli
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0-188.0.dev

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  animated_bottom_navigation_bar: ^1.3.3
  json_annotation: ^4.9.0
  cached_network_image: ^3.4.1
  dio: ^5.7.0
  flex_color_scheme: ^8.0.2
  flutter_cache_manager: ^3.4.1
  flutter_easyloading: ^3.0.5
  flutter_localization: ^0.3.0
  flutter_native_splash: ^2.4.2
  flutter_screenutil: ^5.9.3
  get: ^4.6.6
  image_gallery_saver_plus: ^4.0.0-0.alpha
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  photo_view: ^0.15.0
  provider: ^6.1.2
  pull_to_refresh: ^2.0.0
  qr_flutter: ^4.1.0
  retrofit: ^4.4.1
  wechat_assets_picker: ^9.4.2
  wechat_camera_picker: ^4.3.6
  sp_util: ^2.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.3
  build_runner: ^2.4.14

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/images/
