name: flutter_cli
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  animated_bottom_navigation_bar: ^1.3.3
  cached_network_image: ^3.4.1
  dio: ^5.7.0
  flex_color_scheme: ^8.0.2
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  flutter_localization: ^0.3.0
  flutter_native_splash: ^2.4.2
  flutter_screenutil: ^5.9.3
  get: ^4.6.6
  image_gallery_saver_plus: ^3.0.5
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  photo_view: ^0.15.0
  provider: ^6.1.2
  qr_flutter: ^4.1.0
  retrofit: ^4.4.1
  wechat_assets_picker: ^9.4.2
  wechat_camera_picker: ^4.3.6
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
